[package]
name = "polyjuice-tests"
version = "0.2.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gw-types = { path = "../integration-test/godwoken/crates/types" }
gw-common = { path = "../integration-test/godwoken/crates/common" }
gw-db = { path = "../integration-test/godwoken/crates/db" }
gw-store = { path = "../integration-test/godwoken/crates/store" }
gw-config = { path = "../integration-test/godwoken/crates/config" }
gw-traits = { path = "../integration-test/godwoken/crates/traits" }
gw-generator = { path = "../integration-test/godwoken/crates/generator" }
gw-jsonrpc-types = { path = "../integration-test/godwoken/crates/jsonrpc-types" }
ckb-vm = { git = "https://github.com/nervosnetwork/ckb-vm.git", tag = "0.19.1", features = ["detect-asm"] }
ethabi = "14.0.0"
lazy_static = "1.4"
tiny-keccak = "1.4"
blake2b-rs = "0.2"
serde_json = "1.0"
rlp = "0.5.0"
hex = "0.4.2"
rand = "0.7.3"
env_logger = "0.8.3"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "bench_main"
harness = false
